name: "Workflow Param Test"

on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string
      environment:
        description: 'Environment to deploy to'
        required: false
        type: string
          
  workflow_dispatch:
    inputs:
      app:
        required: true
        type: string
      environment:
        description: 'Environment to deploy to'
        required: false
        type: choice
        options:
          - 'main'
          - 'emu'
          - 'emu-uat'
          - 'er'

jobs:
  do-the-build:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-output.outputs.tag }}
    steps:
      - name: Checkout app source
        uses: actions/checkout@v4
      - name: Get tag from parameter
        if: ${{ inputs.environment != '' }}
        run: echo "tag=$(echo ${{ inputs.environment }} | tr '[:upper:]' '[:lower:]')" | tee -a $GITHUB_ENV
      - name: Get tag from branch name
        if: ${{ inputs.environment == '' }}
        run: echo "tag=$(echo "${GITHUB_REF_NAME}" | tr '/' '-' | tr '[:upper:]' '[:lower:]')" | tee -a $GITHUB_ENV
      - name: Set output
        id: set-output
        run: echo "tag=${{env.tag}}" | tee -a $GITHUB_OUTPUT
      - name: Print the tag
        run: echo ${{env.tag}}

  do-the-deploy:
    runs-on: ubuntu-latest
    needs: [do-the-build]
    steps:
      - name: Deploy to the environment
        run: echo "DEPLOYING ${{inputs.app}} TO ${{needs.do-the-build.outputs.environment}}"
